Repository inureyes/Galtron, pull requests merged in 2018-04, with the labels that each got.

#156 적 위치 개선 #115 issue 해결 (수정)
  gameFunctions.py
Labels: Modes, enhancement, score:5

#161 Fixed a problem that does not show the remaining life when replaying the game.
  gameFunctions.py
Labels: UI/UX, bug, score:3

#150 Resolved issue #83 (Ultimate attack)
  README.md
  bullet.py
  gameFunctions.py
  gameStats.py
  main.py
  scoreboard.py
  settings.py
Labels: Action, Modes, enhancement, score:10

#153 #108 이슈 해결했습니다.
  gameFunctions.py
  scoreboard.py
  settings.py
Labels: Modes, enhancement, score:3

#152 Solved the issue #130, #142, #143, #145
  README.md
  about.py
  bullet.py
  button.py
  gameFunctions.py
  gfx/About_modify.PNG
  gfx/title_modify.PNG
  mainMenu.py
  selector.py
  settings.py
Labels: Graphics, Modes, UI/UX, enhancement, score:5

#146 resolve : #106
  scoreboard.py
  settings.py
Labels: UI/UX, score:4

#137 공격 궤도 변화 #109 issue 해결
  __pycache__/about.cpython-36.pyc
  __pycache__/alien.cpython-36.pyc
  __pycache__/bullet.cpython-36.pyc
  __pycache__/button.cpython-36.pyc
  __pycache__/eBullet.cpython-36.pyc
  __pycache__/gameFunctions.cpython-36.pyc
  __pycache__/gameStats.cpython-36.pyc
  __pycache__/mainMenu.cpython-36.pyc
  __pycache__/scoreboard.cpython-36.pyc
  __pycache__/selector.cpython-36.pyc
  __pycache__/settings.cpython-36.pyc
  __pycache__/ship.cpython-36.pyc
  __pycache__/twoPlayer.cpython-36.pyc
  bullet.py
  data-files/highscore.json
  gameFunctions.py
  settings.py
Labels: Action, Modes, score:5

#151 I solved the issue #125, #134, #74, #107
  alien.py
  gameFunctions.py
  ship.py
Labels: Action, Modes, UI/UX, enhancement, score:10

#155 resolve : #103
  alien.py
  gameStats.py
  gfx/player_blue.bmp
  gfx/player_grey.bmp
  gfx/player_red.bmp
  main.py
  mainMenu.py
  playMenu.py
  ship.py
Labels: Graphics, UI/UX, score:5

#178 Fixed Bullet Amount and etc..
  .gitignore
  data-files/highscore.json
  eBullet.py
  gameFunctions.py
  settings.py
Labels: Action, enhancement, score:3

#148 added speed control option
  README.md
  gameFunctions.py
  settings.py
Labels: Action, Modes, bug, enhancement, score:5

#167 add animations module and Explosion Effect
  animations.py
Labels: Graphics, bug

#177 레이저 색 변경 #130, 적의 모습 바꾸기 #128, 일시정지 기능추가 #72, 맵 크기 넓히기 #113
  README.md
  alien.py
  bullet.py
  gameFunctions.py
  gfx/alien3.png
  gfx/bullet2.png
  settings.py
Labels: Action, Graphics, enhancement, score:2

#188 issue #123
  about.py
  gameFunctions.py
  license
  main.py
  mainMenu.py
  playMenu.py
  settings.py
  sounds/attack.wav
  sounds/control_menu.wav
  sounds/galtron.mp3
  sounds/paused.wav
  sounds/select_menu.wav
  sounds/start_game.wav
  sounds/ult_attack.wav
  twoPlayer.py
Labels: Sound, enhancement, score:5

#195 resolve: #120, #123
  bullet.mp3
  main.py
  mainMenu.py
  scoreboard.py
  ship.py
Labels: Action, Sound, enhancement, score:5

#189 Change About_modify.png and SPEED LIMIT
  gfx/About_modify.PNG
  settings.py
Labels: Action, Graphics, bug, enhancement, score:3

#197 resolve issue #191
  .DS_Store
  bullet.mp3
  gfx/airplane.jpg
  mainMenu.py
  ship.py
Labels: Action, UI/UX, bug, enhancement, score:5

#193 issue #123 추가
  README.md
  __pycache__/about.cpython-36.pyc
  __pycache__/alien.cpython-36.pyc
  __pycache__/bullet.cpython-36.pyc
  __pycache__/button.cpython-36.pyc
  __pycache__/eBullet.cpython-36.pyc
  __pycache__/gameFunctions.cpython-36.pyc
  __pycache__/gameStats.cpython-36.pyc
  __pycache__/mainMenu.cpython-36.pyc
  __pycache__/scoreboard.cpython-36.pyc
  __pycache__/selector.cpython-36.pyc
  __pycache__/settings.cpython-36.pyc
  __pycache__/ship.cpython-36.pyc
  __pycache__/twoPlayer.cpython-36.pyc
  about.py
  alien.py
  gameFunctions.py
  mainMenu.py
  sound_effect/button_clicked.wav
  sound_effect/enemy_explosion.wav
  sound_effect/enemy_shot.wav
  sound_effect/explosion.wav
Labels: Sound, enhancement, score:5

#217 Fixed the issue #180 (Current score overlaps ultimate gauge)
  README.md
  data-files/highscore.json
  gameFunctions.py
  scoreboard.py
Labels: UI/UX, bug, score:4

#226 #206 Change BackGround Image If Player clear 5n Stage
  gameFunctions.py
  gfx/background3.png
  gfx/background4.png
  settings.py
Labels: Graphics, Scene, enhancement, score:5

#227 Add charge shot / Add sound module / Bullet firing bug fixes (#207, #188, #193)
  about.py
  alien.py
  bullet.py
  gameFunctions.py
  main.py
  mainMenu.py
  playMenu.py
  ship.py
  sound_bgms/galtron.mp3
  sound_effect/enemy_explosion.wav
  sound_effects/attack.wav
  sound_effects/bullet.mp3
  sound_effects/button_clicked.wav
  sound_effects/charge_shot.wav
  sound_effects/control_menu.wav
  sound_effects/enemy_explosion.wav
  sound_effects/enemy_shot.wav
  sound_effects/explosion.wav
  sound_effects/paused.wav
  sound_effects/select_menu.wav
  sound_effects/start_game.wav
  sound_effects/ult_attack.wav
  sounds.py
  twoPlayer.py
Labels: Action, Sound, UI/UX, bug, enhancement, score:5

#214 Solve the issue #106 #186
  gameFunctions.py
  settings.py
Labels: Action, enhancement, modification needed, score:3

#234 다음과 같은 기능을 추가했습니다.
  gameFunctions.py
  main.py
  settings.py
  ship.py
Labels: Action, Graphics, enhancement, score:5

#236 C키에 도탄 옵션 추가
  gameFunctions.py
  settings.py
Labels: Action, enhancement, score:4

#240 차지샷 발사 코드를 gamefunc에서 ship으로 이동했습니다.
  gameFunctions.py
  ship.py
Labels: Action, bug, score:4

#245 Fixed the problem that charge shots are always fired. (#231)
  animations.py
  gameFunctions.py
  ship.py
Labels: bug

#251 Relocates irregularly placed top UI (#250)
  gameFunctions.py
  scoreboard.py
Labels: UI/UX, bug, score:5

#259 #172 issue Reset Game
  about.py
  gameFunctions.py
  gfx/About_modify2.png
  main.py
Labels: Action, UI/UX, enhancement, score:5

#260 # 128 적의 모습 바꾸기 수정했습니다.
  README.md
  alien.py
  gameFunctions.py
  gfx/spaceship3.png
  gfx/spaceship4.png
  settings.py
Labels: Graphics, enhancement, score:3

#247 Issue #117
  .DS_Store
  gameFunctions.py
  main.py
  twoPlayer.py
Labels: Action, Modes, modification needed, score:5

#263 Changed model of "blue" ship
  gfx/Alien_Scout.bmp
  gfx/player_blue.bmp
Labels: Graphics, enhancement

#266 resolve the issue #262
  gameFunctions.py
  settings.py
Labels: Action, Modes, enhancement

#271 resolve: #270
  settings.py
Labels: bug, score:3

#273 #229 issue resolve
  gfx/background5.jpg
  gfx/background6.jpg
  settings.py
Labels: Graphics, Scene, enhancement, score:4

#278 2인용 모드 fix했습니다
  alien.py
  main.py
  twoPlayer.py
Labels: Graphics, bug, score:4

#279 Add ship explosion on game
  gameFunctions.py
  twoPlayer.py
Labels: Graphics, enhancement, score:3

#274 #270 점수 배율
  gameFunctions.py
  settings.py
Labels: Modes, bug, score:5

#258 #203 add stage clear sound effect
  gameFunctions.py
  main.py
  playMenu.py
  sound_bgms/galtron.mp3
  sound_effects/stage_clear.wav
  sounds.py
Labels: Sound, modification needed

#287 인트로 영상 추가(issue #112)
  gfx/intro1.png
  gfx/intro2.png
  gfx/intro3.png
  gfx/intro4.png
  gfx/intro5.png
  gfx/intro6.png
  gfx/intro7.png
  gfx/introimage.png
  intro.py
  main.py
Labels: Graphics, Scene, enhancement, score:5

#294 이슈 97, 282 해결 및 메뉴 구현 코드 변경
  about.py
  button.py
  buttonMenu.py
  gameFunctions.py
  gameStats.py
  main.py
  mainMenu.py
  playMenu.py
  scoreboard.py
  settings.py
  settingsMenu.py
  ship.py
  twoPlayer.py
  utilityFunctions.py
Labels: Modes, UI/UX, bug, enhancement, modification needed

#305 성능을 하락시키는 요소 제거 및 최적화 (#302)
  gameFunctions.py
  gfx/life.png
  scoreboard.py
Labels: Maintenance, UI/UX, bug, score:5

#306 효과음 재생 버그 수정 (#303)
  gameFunctions.py
  main.py
  sounds.py
Labels: Maintenance, Sound, bug

#307 Add alienHP and bulletDamage (#99)
  alien.py
  bullet.py
  gameFunctions.py
  main.py
Labels: Action, Game design, enhancement, score:5

#309 멀티 레이어 백그라운드 구현 (#211)
  background.py
  gameFunctions.py
  gfx/backgrounds/stars_back.png
  gfx/backgrounds/stars_front.png
  main.py
  settings.py
Labels: Design, Graphics, enhancement

#301 resolve: #298
  gameFunctions.py
  main.py
Labels: Action, enhancement

#304 비행기 기울어짐 구현 (#183)
  gfx/player_ship/player_ship.png
  gfx/player_ship/player_ship_left1.png
  gfx/player_ship/player_ship_left2.png
  gfx/player_ship/player_ship_left3.png
  gfx/player_ship/player_ship_left4.png
  gfx/player_ship/player_ship_right1.png
  gfx/player_ship/player_ship_right2.png
  gfx/player_ship/player_ship_right3.png
  gfx/player_ship/player_ship_right4.png
  ship.py
Labels: Design, Graphics, enhancement

#285 Resolve issue #102
  .editorconfig
  gameFunctions.py
  gfx/item_heal.png
  item.py
  main.py
  settings.py
Labels: Action, Graphics, enhancement, score:10

#318 resolve #314 (item bugs)
  data-files/highscore.json
  gameFunctions.py
  scoreboard.py
  settings.py
Labels: Modes, bug, enhancement, score:10

#321 Limit life
  gameFunctions.py
  settings.py
Labels: Action, enhancement, score:5

#322 More difficult
  alien.py
  settings.py
Labels: Action, Modes, enhancement, score:5

#332 차지샷 크기 조절 #329
  bullet.py
  gameFunctions.py
Labels: Graphics, bug, score:5

#327 No charging ultimate
  bullet.py
  gameFunctions.py
Labels: Action, Game design, enhancement, score:5

#338 resolve : #336
  gameFunctions.py
Labels: Modes, bug, score:3

#339 Decrease alien life
  gameFunctions.py
Labels: Game design, enhancement, score:3

#325 Resolve #98
  alien.py
  eBullet.py
  gameFunctions.py
Labels: Modes, enhancement, score:10

#343 Add alien blink animation.
  alien.py
  bullet.py
  gameFunctions.py
  gfx/spaceship4_sprite.png
Labels: Design, Graphics, enhancement, score:5

#349 resolve : #347
  gameFunctions.py
Labels: Modes, bug, score:4

#350 Modify boss
  alien.py
  eBullet.py
  gameFunctions.py
Labels: Game design, enhancement, score:5

#354 resolve : #353 #355
  gfx/fixsetting4.png
  gfx/fixsettings1.png
  gfx/item_heal2.png
  item.py
  settingsMenu.py
Labels: Game design, UI/UX, score:5

#352 #299
  gfx/player_blue.png
  gfx/player_gray.png
  playMenu.py
Labels: Design, Graphics, score:5

#357 resolve : #172
  main.py
Labels: Modes, bug, enhancement

#358 resolve : #122
  gameFunctions.py
Labels: Modes, enhancement, score:4

#367 issue #315, issue # 131 ( 기체 공격력 속성추가 및 시계아이템 추가 )
  bullet.py
  eBullet.py
  gameFunctions.py
  gfx/item_time.png
  item.py
  settings.py
  ship.py
Labels: Game design, Modes, enhancement

#368 #362 New item : Shield + bug fixed
  gameFunctions.py
  gfx/item_shield.png
  item.py
  settings.py
Labels: Game design, bug, enhancement, score:5

#383 #373 is solved
  README.md
  about.py
  alien.py
  animations.py
  bullet.py
  button.py
  eBullet.py
  gameFunctions.py
  gameStats.py
  gfx/About_modify2.png
  gfx/Alien_Scout.bmp
  gfx/fixsettings.png
  gfx/gameover.png
  gfx/player_blue.bmp
  gfx/spaceship3.png
  gfx/spaceship4.png
  license
  main.py
  mainMenu.py
  playMenu.py
  requirements.txt
  scoreboard.py
  selector.py
  settings.py
  settingsMenu.py
  ship.py
  sounds.py
  twoPlayer.py
Labels: UI/UX, bug, score:4

#375 시간아이템 배경 투명화해서 다시 올려요!
  gfx/item_time.png
Labels: Design, score:3

#401 resolve : #399 레벨선택 화면에서 메인메뉴로 돌아가는 버튼 추가
  levelMenu.py
  main.py
Labels: Game design, enhancement, score:5

#402 Add Item sound and fix slow item bug
  bullet.py
  gameFunctions.py
  sound_effects/heal_sound.wav
  sound_effects/shield_sound.wav
  sound_effects/slow_sound.wav
  sounds.py
Labels: Graphics, Sound, bug, enhancement, score:5

#389 ship blinks when it is invincible
  __pycache__/about.cpython-36.pyc
  __pycache__/alien.cpython-36.pyc
  __pycache__/bullet.cpython-36.pyc
  __pycache__/button.cpython-36.pyc
  __pycache__/eBullet.cpython-36.pyc
  __pycache__/gameFunctions.cpython-36.pyc
  __pycache__/gameStats.cpython-36.pyc
  __pycache__/mainMenu.cpython-36.pyc
  __pycache__/scoreboard.cpython-36.pyc
  __pycache__/selector.cpython-36.pyc
  __pycache__/settings.cpython-36.pyc
  __pycache__/ship.cpython-36.pyc
  __pycache__/twoPlayer.cpython-36.pyc
  data-files/highscore.json
  gameFunctions.py
Labels: Modes, enhancement, score:4

#408 Fix bug that color of player ship is not changed
  gfx/player_red.png
  gfx/player_ship/blue/player_ship.png
  gfx/player_ship/blue/player_ship_left1.png
  gfx/player_ship/blue/player_ship_left2.png
  gfx/player_ship/blue/player_ship_left3.png
  gfx/player_ship/blue/player_ship_left4.png
  gfx/player_ship/blue/player_ship_right1.png
  gfx/player_ship/blue/player_ship_right2.png
  gfx/player_ship/blue/player_ship_right3.png
  gfx/player_ship/blue/player_ship_right4.png
  gfx/player_ship/gray/player_ship.png
  gfx/player_ship/gray/player_ship_left1.png
  gfx/player_ship/gray/player_ship_left2.png
  gfx/player_ship/gray/player_ship_left3.png
  gfx/player_ship/gray/player_ship_left4.png
  gfx/player_ship/gray/player_ship_right1.png
  gfx/player_ship/gray/player_ship_right2.png
  gfx/player_ship/gray/player_ship_right3.png
  gfx/player_ship/gray/player_ship_right4.png
  gfx/player_ship/player_ship_left1.png
  gfx/player_ship/player_ship_left2.png
  gfx/player_ship/player_ship_left3.png
  gfx/player_ship/player_ship_left4.png
  gfx/player_ship/player_ship_right1.png
  gfx/player_ship/player_ship_right2.png
  gfx/player_ship/player_ship_right3.png
  gfx/player_ship/player_ship_right4.png
  gfx/player_ship/red/player_ship.png
  gfx/player_ship/red/player_ship_left1.png
  gfx/player_ship/red/player_ship_left2.png
  gfx/player_ship/red/player_ship_left3.png
  gfx/player_ship/red/player_ship_left4.png
  gfx/player_ship/red/player_ship_right1.png
  gfx/player_ship/red/player_ship_right2.png
  gfx/player_ship/red/player_ship_right3.png
  gfx/player_ship/red/player_ship_right4.png
  playMenu.py
  scoreboard.py
  settings.py
  ship.py
Labels: Design, Graphics, Maintenance, bug, score:5

#426 게임 오버 화면에서 일시정지 키를 이용해 계속 진행할 수 있는 버그 수정 (#424)
  gameFunctions.py
Labels: bug, score:3

#413 371 ,406
  data-files/highscore.json
  gameFunctions.py
  gfx/player_ship/red/player_ship.png
  main.py
  sound_effects/enemy_damaged.wav
  sounds.py
  speedMenu.py
Labels: Sound, enhancement, modification needed, score:5

#418 Boss's moving to down is removed.
  gameFunctions.py
Labels: Game design, enhancement, score:5

#412 #345 쉴드 이펙트 구현
  README.md
  gameFunctions.py
  gfx/spr_shield.png
  main.py
  sounds.py
  speedMenu.py
Labels: Design, Graphics, enhancement, modification needed, score:5

#422 reslove : #406
  main.py
  speedMenu.py
Labels: UI/UX, bug, score:3

#421 Issues #269 세팅메뉴에 intercept 버튼추가, 플레이중 esc 누를시 게임종료할건지 한번 더 물어봄
  Fonts/Square.ttf
  README.md
  background.py
  data-files/highscore.json
  gameFunctions.py
  gameStats.py
  gfx/explosion-sheet_reverse.png
  gfx/player_ship/red/player_ship.png
  gfx/title_c_reverse.png
  main.py
  scoreboard.py
  settingsMenu.py
  sounds.py
Labels: UI/UX, enhancement, score:3, score:5

#431 Resolved #430
  bullet.py
  eBullet.py
  gfx/eBullet.png
  gfx/old_gfx/About_about.png
  gfx/old_gfx/About_modify.PNG
  gfx/old_gfx/About_modify_old.PNG
  gfx/old_gfx/Alien_Scout.bmp
  gfx/old_gfx/abouttxt.png
  gfx/old_gfx/alien.bmp
  gfx/old_gfx/alien1.bmp
  gfx/old_gfx/alien3.png
  gfx/old_gfx/alienchange.png
  gfx/old_gfx/bullet.bmp
  gfx/old_gfx/bullet.png
  gfx/old_gfx/bullet2.png
  gfx/old_gfx/bullet_colorchange.bmp
  gfx/old_gfx/bullet_colorchange.png
  gfx/old_gfx/cHair.png
  gfx/old_gfx/ebullet.bmp
  gfx/old_gfx/ebullet_colorchange.bmp
  gfx/old_gfx/ebullet_colorchange.png
  gfx/old_gfx/enemy.bmp
  gfx/old_gfx/enemy.png
  gfx/old_gfx/fixsettings.png
  gfx/old_gfx/playe1r.bmp
  gfx/old_gfx/player.bmp
  gfx/old_gfx/player.png
  gfx/old_gfx/player1.bmp
  gfx/old_gfx/player_blue.bmp
  gfx/old_gfx/player_grey.bmp
  gfx/old_gfx/player_red.bmp
  gfx/old_gfx/ship.bmp
  gfx/old_gfx/title(2).png
  gfx/old_gfx/title.png
  gfx/old_gfx/title_modify.PNG
  gfx/old_gfx/untitled.png
  gfx/old_gfx/제목 없음-1 - 복사본.png
  gfx/pBullet.png
  gfx/sBullet.png
Labels: Design, Graphics, enhancement, score:5

#437 issue#434 speedTime 아이템의 매커니즘 변경 해결
  gameFunctions.py
  settings.py
Labels: Game design, enhancement, score:5

#439 일부 들여쓰기 일관성 문제 수정
  gameFunctions.py
Labels: Maintenance, score:2

#436 #432 Bug is fixed
  alien.py
  gameFunctions.py
Labels: Game design, bug, score:4

#445 Fix README.md: #444
  README.md
Labels: Maintenance, score:2

#427 resolved #387(no conflict)
  gameFunctions.py
Labels: Game design, Sound, enhancement, score:5

#411 resolve #393, #398 issue
  gameFunctions.py
  gameStats.py
  settings.py
Labels: Maintenance, bug, enhancement, score:5

#450 Revert wrong commit!
  README.md
  gameFunctions.py
  main.py
  sounds.py
  speedMenu.py
Labels: Maintenance, bug

#452 Add missing parameter
  gameFunctions.py
Labels: UI/UX, bug

#462 resolve #442 word position edit
  gameFunctions.py
Labels: Design

#447 Resolved #238(Pull requested #283, #419)
  main.py
Labels: Sound, bug, score:5

#456 resolve #455
  gfx/heal 1.png
  gfx/heal 2.png
  gfx/heal 3.png
  gfx/shield 1.png
  gfx/shield 3.png
  gfx/shield2.png
  gfx/speed 1.png
  gfx/speed 2.png
  gfx/speed 3.png
  gfx/time 1.png
  gfx/time 2.png
  gfx/time 3.png
  item.py
Labels: Design, Game design, Graphics, score:4

#465 resolve: #464
  settings.py
Labels: Maintenance, Modes, bug, score:4
