Repository inureyes/Galtron, pull requests merged in 2018-03, with the labels that each got.

#60 add Hayeong's info in README.md
  README.md
Labels: enhancement, good first issue

#55 Pull request
  README.md
Labels: enhancement, good first issue

#16 Add Hyunjun Lee's information to README.md
  README.md
Labels: enhancement, good first issue

#18 Add my name
  README.md
Labels: enhancement, good first issue

#54 Add my info in readme
  README.md
Labels: enhancement, good first issue

#20 Add TaeWoong Kong's information to README.md
  README.md
Labels: enhancement, good first issue

#19 Add my name in readme
  README.md
Labels: enhancement, good first issue

#6 add student name
  README.md
Labels: enhancement, good first issue

#22 Add my name in read me
  README.md
Labels: enhancement, good first issue

#40 Add_my_name
  README.md
Labels: enhancement, good first issue

#23 Updated readme
  README.md
Labels: enhancement, good first issue

#24 Add my name in read me
  README.md
  README.md.rej
Labels: enhancement, good first issue

#27 Add my info in readme
  README.md
Labels: enhancement, good first issue

#28 Add-my-info-in-readme
  README.md
Labels: enhancement, good first issue

#30 add my info to readme
  README.md
  __pycache__/about.cpython-35.pyc
  __pycache__/about.cpython-36.pyc
  __pycache__/alien.cpython-35.pyc
  __pycache__/alien.cpython-36.pyc
  __pycache__/bullet.cpython-35.pyc
  __pycache__/bullet.cpython-36.pyc
  __pycache__/button.cpython-35.pyc
  __pycache__/button.cpython-36.pyc
  __pycache__/eBullet.cpython-35.pyc
  __pycache__/eBullet.cpython-36.pyc
  __pycache__/gameFunctions.cpython-35.pyc
  __pycache__/gameFunctions.cpython-36.pyc
  __pycache__/gameStats.cpython-35.pyc
  __pycache__/gameStats.cpython-36.pyc
  __pycache__/mainMenu.cpython-35.pyc
  __pycache__/mainMenu.cpython-36.pyc
  __pycache__/scoreboard.cpython-35.pyc
  __pycache__/scoreboard.cpython-36.pyc
  __pycache__/selector.cpython-35.pyc
  __pycache__/selector.cpython-36.pyc
  __pycache__/settings.cpython-35.pyc
  __pycache__/settings.cpython-36.pyc
  __pycache__/ship.cpython-35.pyc
  __pycache__/ship.cpython-36.pyc
  __pycache__/twoPlayer.cpython-35.pyc
  __pycache__/twoPlayer.cpython-36.pyc
  about.pyc
  alien.pyc
  bullet.pyc
  button.pyc
  eBullet.pyc
  gameFunctions.py
  gameFunctions.pyc
  gameStats.pyc
  mainMenu.pyc
  scoreboard.pyc
  selector.pyc
  settings.pyc
  ship.pyc
  twoPlayer.pyc
Labels: enhancement, good first issue

#31 My name add
  README.md
Labels: enhancement, good first issue

#32 add my info in readme
  README.md
Labels: enhancement, good first issue

#33 Add my name
  README.md
Labels: enhancement, good first issue

#41 add my info
  README.md
Labels: enhancement, good first issue

#42 7
  README.md
Labels: enhancement, good first issue

#50 Add Jinsung An
  README.md
Labels: enhancement, good first issue

#48 add my name YK
  README.md
Labels: enhancement, good first issue

#43 add my name
  README.md
Labels: enhancement, good first issue

#53 Update README.md
  README.md
Labels: enhancement, good first issue

#149 I solved the issue #107
  alien.py
Labels: Modes, UI/UX, enhancement, score:1

#147 added bgm
  __pycache__/about.cpython-36.pyc
  __pycache__/alien.cpython-36.pyc
  __pycache__/bullet.cpython-36.pyc
  __pycache__/button.cpython-36.pyc
  __pycache__/eBullet.cpython-36.pyc
  __pycache__/gameFunctions.cpython-36.pyc
  __pycache__/gameStats.cpython-36.pyc
  __pycache__/mainMenu.cpython-36.pyc
  __pycache__/scoreboard.cpython-36.pyc
  __pycache__/selector.cpython-36.pyc
  __pycache__/settings.cpython-36.pyc
  __pycache__/ship.cpython-36.pyc
  __pycache__/twoPlayer.cpython-36.pyc
  galtron.mp3
  main.py
Labels: Sound, enhancement, score:5
